name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.0
  #english_words: ^3.1.0
  cached_network_image: ^0.4.1
  geocoder: ^0.1.1
  image_picker: ^0.4.1
  #flutter_search_bar: ^2.0.2
  url_launcher: ^3.0.0
  cloud_firestore: ^0.8.0
  barcode_scan: ^ 0.0.3
  qr_flutter: ^1.0.0
  firebase_messaging: ^2.0.0
  firebase_auth: ^ 0.5.20
  firebase_performance: ^0.0.5
  google_sign_in: ^3.0.1
  flutter_facebook_login: ^1.1.1
  #uuid: ^0.5.0
  rxdart: ^0.18.1
  #validator: ^0.0.7
  #circle_indicator: ^ 0.0.7
  dots_indicator: ^0.0.4
  page_view_indicator: ^0.3.0+1
  flutter_secure_storage: ^3.1.1
  location: ^1.1.7
  #vibrate: ^0.0.4
  package_info: ^ 0.3.0
  firebase_storage: ^1.0.2
  image: ^2.0.4
  flutter_webview_plugin: ^0.2.1+2
  flutter_swiper: ^1.1.4
  flushbar: ^0.9.2

dev_dependencies:
  #flutter_test:
    #sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/photo-camera.png
    - images/splashscreen.png
    - images/fb-icon.png
    - images/google-icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
